<script lang="ts">
	import { onMount } from 'svelte';
	import type { PearFile } from '../infrastructure/PearFile';

	export let file: PearFile;

	let clickEffectClass = '';

	const handleClick = () => {
		file.selected = true;
	};

	const handleDoubleClick = () => {
		if (clickEffectClass !== 'double-click-effect') {
			clickEffectClass = 'double-click-effect';
			setTimeout(() => {
				clickEffectClass = '';
			}, 400);
		}

		//FileStructure.openFile(file);
	};

	const handleOutsideClick = (event: MouseEvent) => {
		const target = event.target as HTMLElement;
		const cardElement = document.querySelector('.my-card') as HTMLElement;
		if (!cardElement.contains(target)) {
			file.selected = false;
		}
	};

	onMount(() => {
		// Listen for clicks on the entire document
		window.addEventListener('click', handleOutsideClick);
	});
</script>

<button
	class={'card my-card ' + clickEffectClass}
	on:click={handleClick}
	on:dblclick={handleDoubleClick}
>
	<i class={file.icon} />
</button>
<p class="primary file-name">{file.name}</p>

<style lang="scss" scoped>
	/** Most of the css here is generated by ChatGPT */

	@import '../../scss//style.scss'; //import to use color variable

	.file-name {
		margin-top: 7px;
		color: $primary;
		font-size: 1rem;
		font-weight: 500;
	}

	.my-card {
		display: inline-block;
		padding: 3% 4.5% 3% 4.5%;
		font-size: 4rem;
		color: #909090;
		background-color: #e6e6e6;
		transition: background-color 0.2s ease-in-out, box-shadow 0.2s ease-in-out;
	}

	.my-card:hover {
		background-color: #c0c0c0;
		box-shadow: 0 0.2rem 0.4rem rgba(0, 0, 0, 0.15);
	}

	.my-card.double-click-effect {
		animation: double-click-effect 0.4s ease-in-out;
	}

	@keyframes double-click-effect {
		0% {
			transform: scale(1);
			box-shadow: 0 0.2rem 0.4rem rgba(0, 0, 0, 0.15);
		}
		50% {
			transform: scale(0.97);
			box-shadow: 0 0.1rem 0.2rem rgba(0, 0, 0, 0.1);
		}
		100% {
			transform: scale(1);
			box-shadow: 0 0.2rem 0.4rem rgba(0, 0, 0, 0.15);
		}
	}
</style>
